- name: Ensure HP Linux Imaging and Printing Software is installed
  ansible.builtin.package:
    name:
      - hplip
      - expect
      - gpg
    state: present

- name: Copy install script
  ansible.builtin.copy:
    src: files/hp-plugin-install.exp
    dest: /tmp/hp-plugin-install.exp
    mode: a+rx

- name: Configure HP Linux Imaging and Printing Software
  ansible.builtin.command:
    argv:
      - /tmp/hp-plugin-install.exp
    creates: /usr/share/hplip/prnt/plugins/hbpl1.so
